# ICHIN OS — Limine boot protocol configuration
TIMEOUT=3

# ICHIN Kernel entry
:ICHIN OS
PROTOCOL=limine
KERNEL_PATH=boot:///ichin-kernel
KERNEL_CMDLINE=quiet loglevel=3
MODULE_PATH=boot:///ichin-services.sys
